### ISSUE TITLE
TypeError on bulk_lookup_threats

### ISSUE THREAD

**Issue by Hugo-C** [cert-orangecyberdefense/datalake#30]
### CLI version:
```
$ ocd-dtl -V
2.4.1
```

Type error happen when running:
```
$  ocd-dtl bulk_lookup_threats -a file -i hash.txt 

none of your untyped atoms could be typed
Traceback (most recent call last):
  File "/home/hugo-c/.virtualenvs/my_scratch/bin/ocd-dtl", line 8, in <module>
    sys.exit(main())
  File "/home/hugo-c/.virtualenvs/my_scratch/lib/python3.8/site-packages/datalake_scripts/cli.py", line 97, in main
    Cli()
  File "/home/hugo-c/.virtualenvs/my_scratch/lib/python3.8/site-packages/datalake_scripts/cli.py", line 46, in __init__
    getattr(self, args.command)()
  File "/home/hugo-c/.virtualenvs/my_scratch/lib/python3.8/site-packages/datalake_scripts/cli.py", line 82, in bulk_lookup_threats
    bulk_lookup_threats.main(args)
  File "/home/hugo-c/.virtualenvs/my_scratch/lib/python3.8/site-packages/datalake_scripts/scripts/bulk_lookup_threats.py", line 110, in main
    current_typed_atoms = lookup_atom_types(
  File "/home/hugo-c/.virtualenvs/my_scratch/lib/python3.8/site-packages/datalake_scripts/scripts/bulk_lookup_threats.py", line 182, in lookup_atom_types
    if atoms_values_extractor_response['not_found'] > 0:
TypeError: '>' not supported between instances of 'list' and 'int'
```

hash.txt is just a simple list of hashes separated by new lines

**Comment by Hugo-C** [comment]
Fixed in #31
